---
name: Lint Code Base
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint Code Base
    if: github.repository_owner == 'ls1-sys-prog-course-internal'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Black
        run: cd tests && nix-shell --run "black --check ."
      - name: Mypy
        run: cd tests && nix-shell --run "mypy ."
      - name: Flake8
        run: cd tests && nix-shell --run "flake8 ."
